name: Auto Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # elke dag om middernacht
  workflow_dispatch:       # handmatig triggeren

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository met bot-token
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Update timestamp in README.md
      - name: Update timestamp in README
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s/t=TIMESTAMP/t=$TIMESTAMP/g" README.md

      # Commit and push changes using the bot
      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update GitHub stats timestamp" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
