name: Auto Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:       # manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # automatically uses github-actions[bot]

      # Update timestamp in README.md
      - name: Update timestamp in README
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s/t=TIMESTAMP/t=$TIMESTAMP/g" README.md

      # Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update GitHub stats timestamp" || echo "No changes to commit"

      # Push using the token (via URL)
      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
