name: Auto Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:       # manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository and keep credentials for git push
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # automatically uses github-actions[bot]
          persist-credentials: true          # this is key for git push to work

      # Update timestamp in README.md
      - name: Update timestamp in README
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s/t=TIMESTAMP/t=$TIMESTAMP/g" README.md

      # Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update GitHub stats timestamp" || echo "No changes to commit"

      # Push changes (no URL needed)
      - name: Push changes
        run: git push
